export const SET_PAYMENTS = 'FILTER:PAYMENTS:SET'
export const CLEAR_PAYMENTS = 'FILTER:PAYMENTS:CLEAR'

export const SET_INVOICES = 'FILTER:INVOICES:SET'
export const CLEAR_INVOICES = 'FILTER:INVOICES:CLEAR'
