export const SET_PAYMENTS = 'FILTER:PAYMENTS:SET'
export const CLEAR_PAYMENTS = 'FILTER:PAYMENTS:CLEAR'

export const SET_INVOICES = 'FILTER:INVOICES:SET'
export const CLEAR_INVOICES = 'FILTER:INVOICES:CLEAR'

export const SET_POOL = 'FILTER:POOL:SET'
export const CLEAR_POOL = 'FILTER:POOL:CLEAR'

export const SET_PROOF = 'FILTER:PROOF:SET'
export const CLEAR_PROOF = 'FILTER:PROOF:CLEAR'